# Your Name or Company
title: Hello!

# Description of your website. This is used for social sharing.
description:  A personal site.

# A brief blurb about yourself
content: Nothing to see here â€” move along.

# Add your social links
social:
  - platform: do
    url: /
  - platform: not
    url: /
  - platform: click
    url: /
  - platform: linkedin
    url: /

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "G-KPWR8T9YBW" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
